spring.application.name=RawInsight-back
# MySQL Configuration Details
spring.datasource.url=jdbc:mysql://localhost:3306/rawinsight_db
spring.datasource.username=root
spring.datasource.password=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate configurations to automatically manage tables later
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 3. Free Local AI Connection Engine
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=llama3.2:1b

server.port=8080